### ISSUE TITLE
Icon with sizes ranging from 16x16 to 1024x1024

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#10]
These icons will be used for:
- favicon
- apple-touch icon
- brand icon (on all pages)
- home page icon
- the GitHub organization
- any other accounts associated with admins of codeflash
- bragging about how great your retina display is

**Comment by kristenmills** [comment]
Us retina people would like up to 1024

**Comment by toroidal-code** [comment]
![Codeflash2](https://f.cloud.github.com/assets/2250579/141831/fced4206-7280-11e2-8034-b32d320ff564.png)
Here you go, bros. What do you think?
BTW, the brackets are actually transparencies so they adapt to the background color properly.

**Comment by kristenmills** [comment]
It's pretty hip. I approve.

**Comment by nickserv** [comment]
Is this issue done?

**Comment by nickserv** [comment]
This should be done now.
