### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by toroidal-code** [toroidal-code/codeflash#103]
Should we have some sort of forum or discussion system available for users?

**Comment by nickserv** [comment]
Well, we're at least going to have comments for problems and solutions, right?

**Comment by toroidal-code** [comment]
yeah

**Comment by kristenmills** [comment]
project euler does that. we can do that.

**Comment by nickserv** [comment]
Forums could be nice, but that would require quite a few more controllers and planning. We could always think about it later after the core functionality of CodeFlash is implemented.

**Comment by toroidal-code** [comment]
what about using something like [Discourse](http://www.discourse.org/)

**Comment by nickserv** [comment]
Would we be holding the instance of Discourse and its data, or is it hosted for us?

**Comment by StacyJCarlos** [comment]
I feel that discussions on set topics, such as languages or errors, would be nice, but anything other than that would be extraneous I think. We want to promote communication by looking at comments or talking to other users. Plus having random discussions that have been started by users would be clutter.

If we did do discussions, Discourse seems good.

**Comment by nickserv** [comment]
That's a good point. So you're suggesting we only stick to problem and solution comments?

**Comment by toroidal-code** [comment]
okay, fair enough.

**Comment by nickserv** [comment]
Hm, is this agreed upon? Should we close this?

**Comment by StacyJCarlos** [comment]
I say this can be closed.
