### ISSUE TITLE
Problems are DEAD

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#106]
I don't know what is happening but i can't create new problems. I'm running master locally and it's fine but it's not working in production.

**Comment by nickserv** [comment]
You mean you get an error page when you click the new button? That's probably because you're not an admin. It would be fine if you were.

However, while normal users shouldn't be able to create problems, it would be a good idea to hide that button fro normal users and make the error page nicer.

**Comment by toroidal-code** [comment]
Fixed via database reset.
