### ISSUE TITLE
Edit button not appearing for profile

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#107]
The edit button should appear on a users profile.

**Comment by toroidal-code** [comment]
I'm getting this. On production. Are you not?

**Comment by nickserv** [comment]
I'm also seeing the edit button.

**Comment by kristenmills** [comment]
maybe it works now. i wasn't before.

**Comment by kristenmills** [comment]
no this is definitely a bug. 
If a user isn't an admin, edit profile won't show up on their profile page BUT if they go the list of profiles, they can edit anyones profile.
