### ISSUE TITLE
Add language choice list to creating a solution

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#108]
There should be like a drop down to chose language. Or a typeahead. or a combination of both like githubs.

**Comment by toroidal-code** [comment]
it's supposed to be a dropdown, but there're no languages in the db right now.

**Comment by nickserv** [comment]
We should do a typeahead inside of a dropdown, like [Gist](http://gist.github.com) does for language selection.

**Comment by toroidal-code** [comment]
lol. Let's copy the gist div.

**Comment by kristenmills** [comment]
http://harvesthq.github.com/chosen/

**Comment by toroidal-code** [comment]
ooooh that looks nice.

**Comment by kristenmills** [comment]
I'm thinking also using this for categories for problems.

**Comment by toroidal-code** [comment]
Yeah, that would be nice.

**Comment by StacyJCarlos** [comment]
That does look very clean and would save a lot of time.

**Comment by kristenmills** [comment]
oh wait i did this.
