### ISSUE TITLE
Make sure the development server port is always 3000

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#109]
(for consistency with other Rails projects)

**Comment by toroidal-code** [comment]
set your $PORT env_var to 3000 before you do foreman start.

**Comment by nickserv** [comment]
`export PORT=3000` works for me, but it would be nice if this behavior was the default so we don't need to remember yet another option to start the server. It should be easy for us to change the port in the Procfile anyway.

**Comment by nickserv** [comment]
Oops, closed it by accident.

**Comment by toroidal-code** [comment]
Fixed by foreman deprecation.

**Comment by nickserv** [comment]
To clarify, "rails server puma" is what we're using now, and it defaults to port 3000.
