### ISSUE TITLE
UI mockups

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#11]
Wireframes are fine. Up to you if you'd like your mockups to consist of a theme or not.

**Comment by nickserv** [comment]
If we don't get mockups done during this week, we will do them during our meeting Saturday.

**Comment by toroidal-code** [comment]
I have them

**Comment by smy2748** [comment]
Oh cool.

**Comment by kristenmills** [comment]
does that mean you made them?

**Comment by toroidal-code** [comment]
I have been making them. for about a week now. And now they are being balsamified

**Comment by kristenmills** [comment]
On the home page, integrate a signup with github button. Currently it is just in an arbitrary place on the signup page.

**Comment by kristenmills** [comment]
I'm making mockups for the profile page on the plane. I think we are done after that.

**Comment by nickserv** [comment]
Kristen's mockups are done, so I'll close this issue.
