### ISSUE TITLE
Sign in redirect profile 

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#110]
So I propose we change sign up to just email and they set username and things on first sign in.

**Comment by nickserv** [comment]
So the flow would be like this?
1. User enters email address.
2. User opens link in email where they can start setting up an account.
3. User enters password and other stuff.
4. User fills out profile.
5. Account's write access is unlocked.

**Comment by StacyJCarlos** [comment]
The accounts write access shouldn't be activated until their email is confirmed.

**Comment by kristenmills** [comment]
since username is used for linking, username needs to be specified on sign up. 
So it's 
1. User signs up
2. User clicks link in email
3. User is redirected to edit profile page
