### ISSUE TITLE
Get rid of github sign in.

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#111]
I'm proposing we ditch this feature.  Because of username uniqueness, we can't just take someone's github username. And since we are using username for the show url, we can't just wait around and assign a username later on.  There are ways to do things on first sign in but really everything i've been doing to work round this fact is hacky and a hassle and barely working. So getting rid of this feature probably would be for the best.

**Comment by toroidal-code** [comment]
Okay, that's understandable. If you think it's going to be easier to ditch this feature than to work with it in the future, I don't have any problems.

**Comment by nickserv** [comment]
I'd be okay with this if we still can't find a good way to implement it.

**Comment by kristenmills** [comment]
okay i'm going to remove it. I can explain it better later.

**Comment by kristenmills** [comment]
I'm probably leaving most of the logic in.  Just incase we come up with a better way in the future and want to do it.
