### ISSUE TITLE
Switch to Engine Yard instead of Heroku for production.

### ISSUE THREAD

**Issue by toroidal-code** [toroidal-code/codeflash#113]
Why?
- Heroku does routing meshes wrong. [Heroku's ugly secret](http://rapgenius.com/James-somers-herokus-ugly-secret-lyrics)
- Engine Yard uses true EC2 instances, and gives all the benefits of one.
- Engine Yard supports both Rubinius and Puma, allowing for a truly concurrent server system, with threads being spawned for each request.
- Speed: Compare [Engine Yard](http://codeflash.thewcubed.com) with [Heroku](http://codeflash.herokuapp.com) (turn off caching)
- Scaling. We can easily scale to multiple instances of EC2 and get more power for each instance than an equivalent Heroku dyno.

**Comment by nickserv** [comment]
:+1:

**Comment by StacyJCarlos** [comment]
I can attest that it is MUCH faster.

**Comment by toroidal-code** [comment]
Okay, done. I'm closing this and doc'ing it in the wiki. The deploy server I have running is probably going to end up being staging.
