### ISSUE TITLE
gravatar looks derpy on safari

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#119]
![Screen Shot 2013-02-15 at 11 37 10 PM](https://f.cloud.github.com/assets/1054558/163059/9be57556-77f2-11e2-9a1d-ae72d89a8780.png)

**Comment by nickserv** [comment]
This is on Safari on a retina Macbook Pro?

**Comment by kristenmills** [comment]
yeah.  Chrome works fine on my machine.

**Comment by nickserv** [comment]
Can you try this on Safari on a different machine? I want to know if this is a CSS 3 issue or a retina issue. Then again if it's a retina issue, it _might_ still happen on an iPhone.

**Comment by toroidal-code** [comment]
I can confirm this happens in safari on my mac as well. No retina.

**Comment by toroidal-code** [comment]
Found a fix.
