### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#12]
For source code documentation, we should probably use Yard and aim for 100% documentation coverage across the repo.

For additional documentation, we might want to use a GitHub wiki it it doesn't fit nicely into our readme.

User documentation/tutorials/information should probably go on the site. Now that my High Voltage integration is merged into master and production, creating static pages for this kind of information should be easy.

**Comment by smy2748** [comment]
Yard - yus.

General Documentation on the project should exist within the wiki.  This should include design decisions, feature pros/cons, etc.

Tutorials and FAQs should go on the site, but keeping a page in the wiki on how things SHOULD work would be helpful until the implementation becomes more concrete.  These would pretty much be informal use-cases and would help to make sure that everyone is on the same page in terms of how the system is going to operate.

**Comment by nickserv** [comment]
Agreed.

**Comment by nickserv** [comment]
I'm changing this issue to a planning issue.

Since people seem to be agreeing on putting developer docs in the wiki, code docs in our code with YARD, and user docs on static pages on the site, I'll make issues for any of these tasks that aren't done and I'll close this one.
