### ISSUE TITLE
Investigate using the Ace editor in read only mode for viewing code

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#121]

**Comment by kristenmills** [comment]
it makes sense.

**Comment by nickserv** [comment]
Now that #74 is closed, should we also close this?

**Comment by kristenmills** [comment]
No. I closed 74 because we only need 1 issue open about this topic.

**Comment by nickserv** [comment]
Oh alright, I thought you were ending that discussion. I'll mark that issue as a duplicate.

**Comment by toroidal-code** [comment]
Okay, I'll start working on a branch of feature/ui called feature/acero

**Comment by toroidal-code** [comment]
Okay, I have both pygments and aceRO implemented. Ace requires some janky hacks to get  it working, and there's some weird quirks about it. So I'd prefer to use pygments. Take a look at the two versions, tell me which you think is better.

**Comment by toroidal-code** [comment]
There is also now rouge, which is a replacement for pygments written in ruby. So many lexers.

**Comment by toroidal-code** [comment]
I'm leaning more towards pygments, due to the absolutely insane number of lexers it has: [pygments lexers](http://pygments.org/docs/lexers/) vs [rouge's lexers](https://github.com/jayferd/rouge/tree/master/lib/rouge/lexers)

**Comment by nickserv** [comment]
> There is also now **rouge**, which is a replacement for pygments written in ruby. So many lexers.

![](http://s3.amazonaws.com/mfw-production/image_post/1/medium/96.png)
