### ISSUE TITLE
Rescue from CanCan::AccessDenied and show a more friendly error page to the user

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#123]
For starters, this should get added to `app/controllers/application_controller.rb`:

``` ruby
rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_url, :alert => exception.message
end
```

See https://github.com/ryanb/cancan/wiki/exception-handling.

**Comment by toroidal-code** [comment]
Done. c15e441a

**Comment by toroidal-code** [comment]
There's no need for an error page, as we shouldn't even have a case where a user can access something that they would recieve the AccessDenied exception for.

**Comment by nickserv** [comment]
I disagree. Users can still visit URLs of pages that aren't linked to, even if they aren't allowed to access them. What if a user bookmarks their profile edit page and visits it while logged out? We need to have a friendly UI for these sorts of errors.

**Comment by toroidal-code** [comment]
If I'm logged out, and I try to edit my profile, i get a 500 error, not an AccessDenied. CanCan is smart.

**Comment by nickserv** [comment]
Ah, alright. Let's improve the generic 500 error page instead.
