### ISSUE TITLE
Complete the test suite

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#124]
We should finish all our test suites and try to get code coverage near 100%. 

**Note**: 100% code coverage does **not** mean the software is necessarily being tested enough.

Check them off as they reach 100%/when you feel they've been fully tested

**Controllers**
- [x] achievements_controller
- [ ] application_controller
- [x] comments_controller
- [x] languages_controller
- [x] problems_controller
- [x] profiles_controller
- [x] solutions_controller

**Models**
- [x] ability
- [x] achievement
- [x] category
- [x] comment
- [x] language
- [x] problem
- [x] profile
- [x] solution
- [x] user

**Helpers**
- [ ] application_helper
- [x] problem_helper
- [ ] remote_link_pagination_helper

**Comment by smy2748** [comment]
> No description given.
> No one is assigned
> ![](http://www.reactiongifs.com/wp-content/uploads/2013/02/no.gif)

**Comment by kristenmills** [comment]
I'm calling this done.
