### ISSUE TITLE
Prevent user from submitting more than one solution per problem per language

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#127]

**Comment by toroidal-code** [comment]
per language. One solution, per problem, per language. Cause there might be one I want to do in both Common Lisp, and C, right?

**Comment by nickserv** [comment]
@toroidal-code I agree.

**Comment by kristenmills** [comment]
Yeah. That's what i mean.

**Comment by StacyJCarlos** [comment]
You can edit your solutions correct?

**Comment by kristenmills** [comment]
i'm not sure do we want that? Maybe we should prevent editing of language. Because things will start getting sketchy.
