### ISSUE TITLE
User :login method inaccessible

### ISSUE THREAD

**Issue by toroidal-code** [toroidal-code/codeflash#128]
74709516e25be31dd3eae05f0806c4e96e2814fb
This commit broke the homepage when not logged in.
I wrote a one-liner to fix it, but if my method is doing it wrong, can you please branch and repair it?
9ae4116a33b9d29d7eb2912a52986e68e1d8f184

The line that breaks after removal is `<%= f.text_field :login, :class => 'input-xlarge', :placeholder => 'Email or Username' %>` in the file `/views/user/sessions/_compact.html.erb`.

**Comment by kristenmills** [comment]
no you  did it right. The line you added got removed at some point.
