### ISSUE TITLE
Validate ALL the things! (server and client)

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#13]
Our ActiveRecord models should have validations for anything that needs validation.

Additionally, we should use HTML5's awesome form features for client-side validation. It leads to really gorgeous and useful validation UIs fairly quickly. And if a browser doesn't support that, we can safely call back to server-side validation.

Finally, we might want to set up an issue or wiki page for planning exactly what should be required in out validations.

**Comment by kristenmills** [comment]
I was planning on just doing it eventually when i got bored. But yeah a basic list of exactly what we need would be good.

**Comment by smy2748** [comment]
Open up a wiki page for it.

**Comment by kristenmills** [comment]
Kate has to do it.

**Comment by smy2748** [comment]
Assign, assign.

**Comment by kristenmills** [comment]
See #14

**Comment by smy2748** [comment]
MFW issue already existed:

![MFW](http://www.reactiongifs.com/wp-content/uploads/2013/01/youre-awesome.gif)

**Comment by nickserv** [comment]
Kristen finished doing ActiveRecord validations in one of her pull requests, which just got merged in. Should we close this?
