### ISSUE TITLE
Achievements on righthand side of navbar

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#134]
Why? It doesn't really make sense. It probably should go on the left with solutions and problems.

**Comment by nickserv** [comment]
It's there because it's based on a user's profile. I thought about removing that when a user isn't logged in, but that means users without accounts couldn't see our achievements system.

**Comment by kristenmills** [comment]
except it isn't though. Doesn't it show just the list of achievements? That has nothing to do with a user. The users achievements are on the profile page.

**Comment by nickserv** [comment]
Ah, alright. However, I think we should still have a list of all achievements somewhere for users who aren't logged in.

**Comment by kristenmills** [comment]
Yeah we will. On the left side. Where it should be.

**Comment by kristenmills** [comment]
I'm changing this on feature/ui and closing this issue if no one is opposed.

**Comment by toroidal-code** [comment]
I'm opposed. I like the way it's  being done now, as achievements aren't the core focus of the application, problems and solutions are, which is why they're on the left. As achievements are associated with users, they should be on the right side, where all of the user-specific data and links are kept.

**Comment by kristenmills** [comment]
they aren't associated with users though.

**Comment by kristenmills** [comment]
It makes ABSOULTELY NO SENSE to put a list of all achievements with users. If it was list of user achievements, that's different. but it's not.

**Comment by toroidal-code** [comment]
but it is.

**Comment by toroidal-code** [comment]
when a user is logged in, it shows achievements they have gained, and achievements they have not.

**Comment by toroidal-code** [comment]
when a user is logged out, it shows a list of all possible achievements, at least according to Nicolas. I don't entirely understand why we're showing it when a user isn't logged in, though.

**Comment by kristenmills** [comment]
I thought we were showing a users awarded achievements on their profile page...? The list of achievements should really just be a list of achievements and viewable to anyone whether they are logged in or logged out.

**Comment by toroidal-code** [comment]
Hm. If we're going to do it that way I'm against having a separate achievements page in the first place. I feel it's unnecessary to show achievements that you haven't gotten unless you're logged in. The way xbox does it, it lists all achievements for a game on the game's achievements page, and indicates whether you've gotten them or not via highlighting. But on your own profile page, it only shows the achievements you've gotten. You don't know what achievements a game has unless you're looking at that game. Similarly, I feel we should only show gained achievements for users on other's profile pages, and gained and ungained on current_user's profile page, with the ungained being available via a tab or menu. Users not logged in can view other's achievements, but a list of total achievements shouldn't be a main view. Instead, we could have a list somewhere inconspicuous.

**Comment by kristenmills** [comment]
I guess i wasn't clear. I meant only gained achievements on a users profile. The list was so you could see ungained achievements.

**Comment by kristenmills** [comment]
There needs to be a list of achievements that you haven't earned somewhere easily accessible.  A user would want to know that. But I thought on the profile page, that's where you would see the achievements a user has gotten so others can see the achievements awarded to the user.

**Comment by toroidal-code** [comment]
Yeah, there needs to be a list, but since it isn't a core focus of the system, I don't think it should be in the navbar.

**Comment by kristenmills** [comment]
maybe just on a users page. there is a small link under the achievements they received that is like view all achievements.

**Comment by toroidal-code** [comment]
yeah, that'd work.

**Comment by nickserv** [comment]
Is there a consensus on this issue yet?

**Comment by kristenmills** [comment]
i think consensus is removing achievements from the navbar and put a link to it somewhere else.

**Comment by nickserv** [comment]
I agree.

I'm thinking we could have a link to the user's achievements on his/her profile, and a link to your own profile (if you're logged in) somewhere on the problems page or the home page.

**Comment by kristenmills** [comment]
I agree. should we close this?

**Comment by nickserv** [comment]
@toroidal-code @kristenmills Is this decision done?

**Comment by kristenmills** [comment]
i think

**Comment by kristenmills** [comment]
but it needs to be implemented

**Comment by nickserv** [comment]
This is a planning issue. Do you want to close this and make another for implementing it? You can assign yourself to it if you want.

**Comment by kristenmills** [comment]
sure
