### ISSUE TITLE
All admins

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#14]
We should all probably be admins. 
Also re-enable the wiki.

**Comment by nickserv** [comment]
Me and toroidal-code should already be admins. I'll add you if she's OK with that.

I'll bring the wiki up in the next half hour or so.

**Comment by smy2748** [comment]
All I ask is for a wiki and the ability to edit it.

**Comment by toroidal-code** [comment]
Okay, all of you now have admin access to the repo, not the org, and a wiki has been enabled.
