### ISSUE TITLE
Flash notices display twice

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#143]
![Screen Shot 2013-02-22 at 7 52 14 PM](https://f.cloud.github.com/assets/1054558/187334/571d430c-7d53-11e2-9396-c3764c338063.png)

**Comment by toroidal-code** [comment]
yeah, I noticed this too. forget to make an issue.

**Comment by kristenmills** [comment]
yeah i've been meaning to make this issue forever lol.

**Comment by toroidal-code** [comment]
Can you verify this fix?

**Comment by kristenmills** [comment]
works for me.

**Comment by toroidal-code** [comment]
Awesome.
