### ISSUE TITLE
Consider moving to Rails 4 (beta) and Ruby 2 (stable) before Rails 4 is stable

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#150]
**See**:
- http://weblog.rubyonrails.org/2013/2/25/Rails-4-0-beta1/
- Issue #148 (Ruby 2) 
- Issue #132 (Rails 4) 

**Quote from the official Rails blog**:

> Hot on the heels of the first production version of Ruby 2.0 comes the first beta version of Rails 4.0. The two form a great pair and are already running in production on a number of applications, including Basecamp Breeze. In fact, Ruby 2.0 is the preferred Ruby to use with Rails 4.0.

Given that Rails 4 is known to work nicely with Ruby 2, Ruby 2 has faster Rails boot times (and other performance improvements), and that Ruby 2 is recommended, I think it may be a good idea for us to fully switch to Rails 4 now, instead of waiting until Rails 4 is stable. Rails 4 is fairly sturdy for a beta, and by the CodeFlash's initial release is ready for a significantly sized userbase, Rails 4 should be fully stable. As a result, I feel we should work more on Rails 4 support now, instead of delaying that until after it's stable. Besides, we'll want to eventually support Rails 4 and Ruby 2 anyway.

**Note about Rubinius**:
Because we're using Rubinius, if we stick with it, it will take longer until we can use Ruby 2 in production. However, we can still use Rails 4 and Rubinius in 1.9 mode if need be. In that case, we should stick with Rails 4 and Ruby 1.9.3 (or Rubinius in 1.9 mode) for all development and production environments until Rubinius supports Ruby 2.0.

**Comment by toroidal-code** [comment]
I'm fine with moving to rails 4, as long as our resident experts @kristenmills and @smy2748 are alright with it.

**Comment by nickserv** [comment]
Alright, cool. So you'd want us to stick to Rails 4 and Ruby 1.9.3 for everything for now? I can agree to that, as long as we're doing it because of Rubinius.

**Comment by nickserv** [comment]
We have reached a final decision. We will:
- Develop for Rails 4.0 and Ruby 1.9.3 (and use them in testing and production).
- Keep using Rubinius in 1.9 mode.
- Merge the rails4 branch into dev.
- Upgrade to Ruby 2.0 whenever Rubinius starts supporting it (or if we ever stop using Rubinius in production).

Even though we're not totally done moving to Rails 4.0, the build is passing and this is a planning issue, so I will close this anyway.
