### ISSUE TITLE
Long problem titles cause overlaps in problem views

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#151]
![Screen Shot 2013-02-26 at 4 46 23 PM](https://f.cloud.github.com/assets/1054558/198529/163663e2-805e-11e2-902a-a0f2dde11fc9.png)

**Comment by nickserv** [comment]
What is this for? Just problems?

**Comment by kristenmills** [comment]
yeah.

**Comment by nickserv** [comment]
Alright, I updated the title of this issue.

**Comment by nickserv** [comment]
This happens because CSS isn't wrapping text when there are no whitespace characters. It's fine if there are long titles with reasonable numbers of spaces in them. We just need to make sure that long, whitespace-free strings can get forcibly wrapped anyway.
