### ISSUE TITLE
Getting rid of collapsibles

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#153]
I propose getting rid of the collapsible wells for viewing solutions and things. They are kind of ugly and unintuitive.

**Comment by nickserv** [comment]
So you just have to have them expanded permanently and otherwise look the same? Or what?

**Comment by kristenmills** [comment]
I don't know exactly how it should look yet. either the way they are or maybe blog post style-esque. I don't know.

**Comment by toroidal-code** [comment]
Well, they still don't match the mockups, so why don't we work towards getting them to that point and then decide if collapsing is a good idea or not?

**Comment by nickserv** [comment]
I like that idea, Kate. Besides, it should be fairly easy for us to toggle whether or not we want the collapse functionality.

**Comment by kristenmills** [comment]
How they look is not the major problem. The unintuitiveness is.  So making the match the mockup is not going to change my opinion. I've said this 100 times to @thenickperson and it is in another issue but i will reiterate: The fact i click on that title link and it takes me to a new page is a usability no no. Clicking that link should expand the collapsible not just clicking anywhere other than the link. And right now, there is no where to put that link other than right there. So unless someone comes up with a place for the link that goes to the show page, i'm firmly against collapsibles. If they look like the mockups, they'll probably look nicer but that doesn't fix the problem i have with collapsibles.

**Comment by toroidal-code** [comment]
Hrm. alright. I think we need some sort of toggle other than the 'bar' itself.

**Comment by kristenmills** [comment]
it has to be everywhere in the bar or nothing at all. That's the issue. What the user is going to do most likely is click the link thinking it will expand the code but it ends up taking you to a new page. I did this my first time doing it. I showed it to brunwasser and he did the same thing and agrees with me.

**Comment by toroidal-code** [comment]
Like a part of the code drop-down appears on hover-over, with a 'click here to expand' link or something. that link would then change to a 'click here to hide' when the code is expanded. the problem then is how to link to the solution itself.

**Comment by toroidal-code** [comment]
Okay, so we need immediate visual feedback or none at all, is what you are saying?

**Comment by kristenmills** [comment]
look at [bootstrap accordions](http://twitter.github.com/bootstrap/javascript.html#collapse). That's how they should be done. But yes that's basically what i'm saying.

**Comment by toroidal-code** [comment]
okay, i'm going to see how the hover works, but I like the way that boostrap accordians does it, so we might end up doing it that way. A separate link somewhere in the expanded form should probably be what links to the solution itself.

**Comment by kristenmills** [comment]
That would be better. I can live with the bootstrap way. As long as we make them look nice and find a proper place to put the link. We also have the option of doing the gist way where you click the code body itself to go to the solution page itself.

**Comment by toroidal-code** [comment]
That might work well. As long as we make it clear that clicking does indeed do something, like with normal links. Is there a way to make divs hrefs?

**Comment by kristenmills** [comment]
i haven't looked into the actual implementation to be honest.

**Comment by kristenmills** [comment]
i'm closing this issue because i'm over it.
