### ISSUE TITLE
Should we really be using CoffeeScript instead of JavaScript?

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#155]
[CoffeeScript](http://coffeescript.org/) is a language that offers syntax sugar and other features for client-side code.
Like what SASS is to CSS, CoffeeScript converts to JavaScript. And just like SASS, Rails 3 supports CoffeeScript by default, and compiles it to JavaScript for you.

Currently, we're sticking pretty much to Rails's default behavior with CoffeeScript. CoffeeScript's gem is included in Codeflash's Gemfile, and we can put both CoffeeScript **and** JavaScript scripts in app/assets/javascripts.

Now, the question is, do we want to use CoffeeScript over JavaScript?

**Advantages**:
- CoffeeScript has much nicer, more Ruby-like syntax than JavaScript.
- JavaScript does some very silly things, while CoffeeScript has several safeguards to prevent unwanted behavior. (For example, if you forget to use the "var" keyword to define new variables in JavaScript, they will suddenly get global scope with no warnings! CoffeeScript protects you from this behavior).
- Rails already handles CoffeeScript conversion for us in the asset pipeline, and we can even use it with normal JavaScript.
- CoffeeScript should work nicely with jQuery (which we should be using either way).
- CoffeeScript is a Rails convention, but JavaScript is not. Rails follows convention over configuration.

**Disadvantages**:
- It's another thing for everyone in our team to learn. **Update:** It's really not that hard to learn, and there's a good [JavaScript to CoffeeScript](http://js2coffee.org/) tool.
- ~~More assets will need to be compiled.~~ Not a problem, Rails does all of this for you anyway.
- ~~Depending on how we handle AJAX on the client side, we might still need to write JavaScript code.~~ If needed, you can embed JavaScript in CoffeeScript.
- JavaScript is a very weird, beautiful (not syntactically), and misunderstood language. If you don't already know JavaScript, it will be even harder to understand the programming concepts of CoffeeScript, since many of them will be based around JavaScript. **Update:** Somewhat true, but CoffeeScript does a fairly good job of being a new syntax for JavaScript instead of being a completely different language, and it's not that hard to understand.
- CoffeeScript code might hide unexpected behavior on the JavaScript end of things, so JavaScript code may be more straightforward in some cases (depending on how experienced the developer is). **Update:** This might be an issue, but we can always check the compiled JavaScript (it should be fairly readable in the development environment).
- While learning CoffeeScript is probably easier for those who don't already know JavaScript, it's important for web developers to understand JavaScript, as it is a standard. **Update:** True, but CoffeeScript is the standard for Rails.

**Note**:
CoffeeScript is very easy to disable, so we should not worry about how much effort it would take to switch to plain JavaScript.

**Disclaimer**:
~~I've never used CoffeeScript before, but I have done a little research into it.~~ I ~~also~~ don't really know AJAX yet.

**Comment by nickserv** [comment]
I am personally slightly against us using CoffeeScript, mainly because of the disadvantages I already listed above. However, I would not be totally opposed to us using CoffeeScript though, and it could be a cool thing for us to learn (I mean, it is a Rails standard after all).

**Comment by kristenmills** [comment]
i have no real opinion on the matter.

**Comment by nickserv** [comment]
To clarify, we're keeping CoffeeScript, and also using JavaScript when necessary/a good idea.

**Comment by nickserv** [comment]
**Note:** Even though we've already reached a decision on this, I updated my opinions on CoffeeScript in the description now that I actually know some of it.

**Comment by pretzelpanda13** [comment]
Hi nicolas, have you tried mixing the combination of javascript and coffeescript? we are in a process of migrating existing codebase of javascript to coffeescript
