### ISSUE TITLE
Halfling-glyphicons are not being precompiled.

### ISSUE THREAD

**Issue by toroidal-code** [toroidal-code/codeflash#158]
As you can see by going to our site [Codeflash](http;//codeflash.thewcubed.com), the halfling-glyphicons are not being compiled by assets:precompile.

**Comment by nickserv** [comment]
This is just an issue for production, right? And is this an issue for all production deploys?

**Comment by toroidal-code** [comment]
it's an issue for asset compilation. not just for production. on dev the asset pipeline takes over, and serves it.

**Comment by toroidal-code** [comment]
Closed by 2ae00f89dec711c7c8596ac07a8cc7e6f2fe356b
