### ISSUE TITLE
Anchors for paginated solution pages

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#159]
So we should probably figure out how to add anchors for our pagination so i can go to any page.

**Comment by nickserv** [comment]
http://stackoverflow.com/questions/565145/best-way-to-get-will-paginate-working-with-ajax

**Comment by toroidal-code** [comment]
@thenickperson I didn't use that at all. The Rails way to do it is like this: https://gist.github.com/jeroenr/3142686

**Comment by toroidal-code** [comment]
btw, you should be able to go to page two by going to /solutions?page=2

**Comment by nickserv** [comment]
Kate, does moving between `/solutions?page=1` and `/solutions?page=2` require page loads, or can it be done via AJAX? If we can't do it with AJAX (I don't think we can), we need to use anchors.

**Comment by toroidal-code** [comment]
See: http://stackoverflow.com/questions/1134280/update-url-on-ajax-call, http://stackoverflow.com/questions/136458/change-the-url-in-the-browser-without-loading-the-new-page-using-javascript

**Comment by toroidal-code** [comment]
It requires page loads. It seems the right way to do this is using something like [history.js](https://github.com/balupton/history.js)

**Comment by nickserv** [comment]
I'm confused, why do we need HTML 5 history for this? Shouldn't we just use # URLs instead?

**Comment by kristenmills** [comment]
i have no clue how to do anchors and will_paginate. i don't know if it is possible.

**Comment by toroidal-code** [comment]
Will_paginate doesn't generate anchors. it generates links like /solutions?page=5. But we can still update the url with this state, the way it would naturally be done if not for ajax.
