### ISSUE TITLE
Test location changes in Rails 4

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#161]
So rails 4 changes test locations in the following ways:

app/models -> test/models (was test/unit)
app/helpers -> test/helpers (was test/unit/helpers)
app/controllers -> test/controllers (was test/functional)
app/mailers -> test/mailers (was test/functional)

we should change our stuff to these locations.

**Comment by nickserv** [comment]
That's pretty awesome. Do we only need to move directories and files around?

**Comment by kristenmills** [comment]
yeah i think so.
