### ISSUE TITLE
Best Solution Achievements

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#163]
Do we want to just have the "Best solution" achievement and that is a generic achievement awarded for each language and problem and you can just win it multiple times. Or do we want to have FizzBuzz in Haskell best solution and etc?

**Comment by nickserv** [comment]
Is this separate from the concept of a best solution for a problem, or does this replace that? As for achievements, we could do both. Get an achievement if you get the absolute best achievement for a problem (across languages), and get more if you can get best solutions in specific languages (best Ruby solution, best Scala solution, etc.).

**Comment by slownhuffmeister** [comment]
The question is more how are we implementing it not whether it exists. Sorry if that wasn't clear.

**Comment by slownhuffmeister** [comment]
I'm on the wrong account.

**Comment by kristenmills** [comment]
i am no longer on the wrong account

**Comment by smy2748** [comment]
I think a generic best solution one would be the best to do.  We don't want to be creating new achievement things for each problem ever created.

**Comment by kristenmills** [comment]
Decision:
Best Solution overall
Best Solution For [langauge Name here]
