### ISSUE TITLE
Flood Detection or CAPTCHAs

### ISSUE THREAD

**Issue by toroidal-code** [toroidal-code/codeflash#164]
I think using some sort of validation for user creation would be a good idea. Like reCaptcha.

**Comment by nickserv** [comment]
I think we should have a reCaptcha on every registration form. We shouldn't need captchas after that.

**Comment by smy2748** [comment]
@thenickperson  :+1:

**Comment by nickserv** [comment]
It seems like everyone is agreeing with my previous comment, so I'll close this issue.
