### ISSUE TITLE
Achievements on top or bottom

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#165]
Go look at the profile Mockup on the wiki. Achievements are currently on the bottom. I think that's where they should go but I know @toroidal-code said she wants them on top. So I'm putting it to a vote.
Respond with your decision
**Note:** I'm in the process of implementing this right now and I'm going to do achievements bottom but that doesn't mean i've made the decision for the group and am going rogue. I'm just at an airport and bored and will move it if needed.

**Comment by smy2748** [comment]
Could someone make a mockup of the achievements at the top for comparison.  They look good on the bottom, but it might just be because the mockup exists with them at the bottom and my brain is poo0pooing the other idea because it doesn't want to have to imagine them at the top.

**Comment by nickserv** [comment]
@smy2748 :+1:

**Comment by kristenmills** [comment]
Achievements under profile is the agreement
