### ISSUE TITLE
Font awesome

### ISSUE THREAD

**Issue by toroidal-code** [toroidal-code/codeflash#168]
Asset:precompile is failing to compile glyphicons. We should be using font-awesome.

**Comment by nickserv** [comment]
I'm not sure if this will fix our issues with assets. In terms of assets, we will need an extra font file for font-awesome, instead of an extra image file for glyphicons.

However, there's a chance this will fix it, and I like font-awesome anyway, so let's do this.

**Comment by kristenmills** [comment]
I did this
