### ISSUE TITLE
Use a "Later" milestone which we can assign issues to that we want to deal with later

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#170]

**Comment by smy2748** [comment]
This appears to have been completed

**Comment by nickserv** [comment]
I realize my title for this issue was a bit misleading, but I intended on closing this issue only after I comb over all the issues and pin "Later" onto things that need it. I'll reopen this issue until I'm done with that.

**Comment by smy2748** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2013/03/coy-dunno.gif)

K bro.

**Comment by nickserv** [comment]
Issues are assigned now.
