### ISSUE TITLE
Replace (almost) all configs with Rails 4 defaults

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#172]
We'll want to run `rails new`.

Exceptions:
-  routes
- all database configs
- deploy
- puma
- nginx

**Comment by nickserv** [comment]
Is this done? I think we're at least very close, though I'm not sure if @toroidal-code needs to update deploy/puma/nginx things.

**Comment by toroidal-code** [comment]
@thenickperson did you modify the configs in any way that would alter the deploy process?

**Comment by nickserv** [comment]
If we weren't already doing this, I believe assets need to get compiled in production first (instead of sending production the compiled assets). Besides that, I don't think so, but I'm not completely sure.

**Comment by toroidal-code** [comment]
asset compilation works properly, from what I can tell.

**Comment by nickserv** [comment]
This seems done, should we close it?
