### ISSUE TITLE
Flagging

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#173]
We probably should have some sort of flagging/report a comment/solution system.

**Comment by nickserv** [comment]
:+1:

For now, are we going to only let admins do this? Or should we also add moderator accounts?

**Comment by kristenmills** [comment]
admins == moderators at this point

**Comment by nickserv** [comment]
Sounds good, we can handle moderator permissions later as the site grows.

**Comment by toroidal-code** [comment]
agreed.

**Comment by nickserv** [comment]
This is done, but it's not merged into master yet.
