### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#175]
Need them

**Comment by nickserv** [comment]
He wants more carrots, and breadcrumbs!

**Comment by nickserv** [comment]
What do we need breadcrumbs for?

**Comment by kristenmills** [comment]
look at the mockups

**Comment by toroidal-code** [comment]
We should use the bootstrap breadcrumbs.

**Comment by nickserv** [comment]
@toroidal-code :+1:

**Comment by kristenmills** [comment]
that's the plan.
