### ISSUE TITLE
twitter bootstrap rails instead of bootstrap sass

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#176]
So i propose switching to twitter bootstrap rails. It has built in generators so that when we generate things, they are already bootstrap themed and it also has really nice helpers for breadcrumbs and flash while bootstrap sass gives us nothing.

So that's my opinion. I've converted it on my local copy. I'll wait for a response before committing.

**Comment by kristenmills** [comment]
also has font-awesome by default

**Comment by toroidal-code** [comment]
How would this change the asset pipeline, and what sort of setup is required to get it working?

**Comment by kristenmills** [comment]
No setup. Literally just replacing the gem. I've already done all the work. It took 2 seconds.

**Comment by kristenmills** [comment]
like once i commit it, there is nothing any of you guys have to do but `bundle`

**Comment by nickserv** [comment]
Doesn't bootstrap-sass give us mixins that we can't use with LESS versions of Bootstrap?

**Comment by kristenmills** [comment]
Yeah but we aren't even using them so that's not a very good reason to keep it around. Twitter-bootstrap-rails has features that i would like to use so that's why I'm proposing it.

**Comment by nickserv** [comment]
True, I just wanted to mention that so everybody is aware.

I'm fine with twitter-bootstrap-rails. Do you have a branch for it?

**Comment by kristenmills** [comment]
it's on feature/ui. It's not a large enough change to deserve it's own branch. I'll commit it then.

**Comment by nickserv** [comment]
Alright, sounds good.
