### ISSUE TITLE
condense upvotes and downvotes into just one votes column

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#177]
Makes more sense.

**Comment by nickserv** [comment]
I disagree. 2 upvotes and 1 downvote is very different from 1,001 upvotes and 1,000 downvotes.

**Comment by kristenmills** [comment]
Well at the end of the day it's going to be displayed as 1 so what's the difference.

**Comment by nickserv** [comment]
But users should be able to at least see how many votes back up a given score for something.

**Comment by kristenmills** [comment]
I didn't know that was a thing we were displaying to the users.

**Comment by nickserv** [comment]
I think we should keep them separate in the backend, and maybe merge them in the UI.

Advantages:
- it's easier to tell how many people voted total
- it's easier to show upvotes and downvotes to the user separately
- we can easily change the voting algorithm on the fly (if need be) without modifying the number of upvotes and downvotes in the backend

**Comment by kristenmills** [comment]
Okay valid points.
