### ISSUE TITLE
Decide on a chatroom and/or meeting times (if needed)

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#18]

**Comment by smy2748** [comment]
irc irc irc irc irc irc irc irc

**Comment by toroidal-code** [comment]
I'm creating an Irc server. it should be up later tonight

**Comment by nickserv** [comment]
Whenever the IRC is working, I will take down our Google+ community. Let me know if anyone opposes this.

**Comment by smy2748** [comment]
G+ may be better for persistent posts (for whatever reason we may need them) but irc for group chat.
