### ISSUE TITLE
Consider switching to Bootstrap 3 before it (Bootstrap) is released

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#204]
Bootstrap 3 brings a lot of awesome changes, especially with mobile-first responsive layouts, but it also can break a few older Bootstrap features. I think we should work on transitioning to it before it's fully released, just like we're doing with Rails.

[Bootstrap 3 changes](https://github.com/twitter/bootstrap/pull/6342) (very long and detailed)

**Comment by nickserv** [comment]
It seems like nobody is really interested in this besides me, and there aren't that many good gems for Bootstrap 3 yet. Should I close this and we can transition to Bootstrap 3 when it's stable?

**Comment by kristenmills** [comment]
yeah
