### ISSUE TITLE
Switch to Rails 4 stable

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#206]
- [x] use Rails 4.0.0 stable in the Gemfile
- [x] don't use unstable/edge versions of other dependencies (if possible)
- [x] remove the assets group from the Gemfile (see [Upgrading to Rails 4.0](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0-gemfile))
- [x] ~~remove CSS and JavaScript files in `vendor/assets`~~
  - ~~Those assets should be moved to `app/assets` or required via sprockets/imports in `application.js`/`application.css.scss`.~~
- [x] update configs and other files as needed with `rake rails:update`
- [x] add recommended gems to the Gemfile if it makes sense (turbolinks, arel, etc.)

**Comment by StacyJCarlos** [comment]
Rails 4 did remove the assets group so we can scrap it.

**Comment by nickserv** [comment]
Oh, did you delete that from my issue description? I can add it back.

If I remember correctly, I originally posted this with 5 checkboxes, and I'm only seeing 4. I could be wrong though.

**Comment by StacyJCarlos** [comment]
Yeah, i didn't how to do slashes.

**Comment by nickserv** [comment]
What do you mean by "slashes"?

**Comment by StacyJCarlos** [comment]
When you show the original test but crossed out to show it has been omitted.

**Comment by StacyJCarlos** [comment]
Got ya thanks.

**Comment by toroidal-code** [comment]
double tildes ~~so~~

**Comment by nickserv** [comment]
I can do some more of these things tonight.

**Comment by nickserv** [comment]
Correction: We don't need to remove CSS/JS files from `vendor/assets`. We just needed to take care of other files in `vendor/assets`, but we already did this.

> In Rails 4.0, precompiling assets no longer automatically copies non-JS/CSS assets from vendor/assets and lib/assets. Rails application and engine developers should put these assets in app/assets or configure config.assets.precompile.

See http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0-vendor-plugins
