### ISSUE TITLE
Consider making new files for custom application-wide styles/scripts

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#207]
We currently have some SCSS code in `application.css.scss` and some JavaScript code in `application.js`. While this is possible, Rails advises against it (and it might even make asset compiling slower in some cases). I think it would be cleaner if we had a `base.css.scss` file for app-wide SCSS and a `base.js.coffee` file for app-wide CoffeeScript. This has the added advantage of letting us use CoffeeScript (instead of JavaScript) for app-wide scripts.

**Comment by StacyJCarlos** [comment]
I agree. If they are going to be used in multiple places and especially if it compiles faster.

**Comment by nickserv** [comment]
We're doing this, it just hasn't been merged into master yet. Since this is a planning issue, I'm closing it.
