### ISSUE TITLE
Agree on CodeFlash, Codeflash, or Code Flash for the official name

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#21]
Please write your preferred name in a comment to vote. #youonlyvoteonce #yovo

**Comment by toroidal-code** [comment]
Codeflash

**Comment by kristenmills** [comment]
CodeFlash

**Comment by nickserv** [comment]
Code Flash

If we need a tiebreaker, my second favorite is CodeFlash.

**Comment by StacyJCarlos** [comment]
Codeflash seems the best bet for 2 (possibly 3) reasons
1a. If I google code flash I will get how to make flash games
1b. Its one word so it will be easier to find
2. Flash is already a thing

**Comment by nickserv** [comment]
It seems like Codeflash has won. Let's stick with that.
