### ISSUE TITLE
Use PostgreSQL for all environments

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#25]
This should happen on a new `feature/postgre` branch.

We should do the following before merging this change into dev/master:
- [x] use the postgre gem always instead of sqlite3
- [x] update the config files to tell Rails to use postgre instead of sqlite3
- [x] documentation describing the entire setup process (this should probably be in the wiki)

**Comment by toroidal-code** [comment]
I'm going to close this, as I'm merging feature/postgre into dev. I've tested that PostgreSQL works on two of my machines, Linux and a Mac, so I consider this stable.
