### ISSUE TITLE
Consider letting problems be voted on

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#28]
If we do this, users could vote on problems just like solutions. This would make it easier to let non-mods post problems. If we don't do this, we can judge how much users like a problem by popularity or solution count instead.

**Comment by nickserv** [comment]
I think we should do this so we could make better problems appear more frequently (regardless of difficulty) and filter out bad problems.

However, I don't think problem votes should affect anyone's score (unless we allow normal users to post problems).

**Comment by smy2748** [comment]
Possibly, but I'm not sure if we should focus on this atm.  I'd think that the ranking would need to be fleshed out more beofre we decide how to handle this.

**Comment by nickserv** [comment]
:+1:

Does anyone else want to save this for later?

**Comment by smy2748** [comment]
Let's push-pop this shit.

**Comment by nickserv** [comment]
Let's do this later.
