### ISSUE TITLE
Language Families

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#29]
I think Language Families should be done away with.  The purpose of language families was to prevent copy pasta. But really we are limiting people. We shouldn't not allow people to do Objective C and C just because someone COULD be a troll and put C in the Objective C section. But really we don't need to prevent that because the community could vote it down.  So i'm voting against them.

**Comment by nickserv** [comment]
:+1:

**Comment by toroidal-code** [comment]
hmmm. okay. I see what you're saying. If the community is actually active in pushing down blatant rip-offs, I don't have a problem with that.

**Comment by nickserv** [comment]
We could also have some sort of override for mods, so they can shut down bad solutions when the other users don't.

**Comment by toroidal-code** [comment]
I think that's a good idea. We need to have some sort of closing system similar to StackOverflow's "Unconstructive question" where multiple mods can decide to shut down a solution

**Comment by nickserv** [comment]
Good idea. We could also have other mod flags for solutions/problems/etc. if need be.

**Comment by kristenmills** [comment]
Alright if we all agree with this, I'm going to delete the scaffold.

**Comment by nickserv** [comment]
Sounds good. Is anyone against this idea?

**Comment by toroidal-code** [comment]
I'm going to consider this issue closed, as it appears the models have been removed.
