### ISSUE TITLE
Gemnasium page isn't set up properly

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#3]
https://gemnasium.com/codeflash/codeflash

For some reason, Gemnasium says "This project is not monitored, Gemnasium won't track changes." It's possible that there isn't a free tier plan with support for organizations, or we just need a different kind of Gemnasium account.

**Comment by nickserv** [comment]
I sent a message to their customer support. I'll let you know what happens.

**Comment by kristenmills** [comment]
kk

**Comment by nickserv** [comment]
I got Gemnasium support to help me manually update the dependency status, so now the page isn't empty/broken.

I will look into adding this repo to my Gemnasium account so I can update it manually/automatically in the future, though I will close this issue now because the Gemnasium page for this repo is currently up to date.
