### ISSUE TITLE
Change points for a user

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#30]
User probably shouldn't have a points field. We should just have a points method that gets the sum of all the points they've earned through solutions plus the number they've earned through achievements. 

I'll do it later.

**Comment by nickserv** [comment]
How could we handle caching different parts of the user's score so we don't need to do tons of DB lookups whenever a profile is loaded?

**Comment by kristenmills** [comment]
The thing is we are going to be doing those queries anyway so it doesn't matter. We'd be calculating total number of points on the profile page. Also on the profile page, we'll be querying to get all solutions submitted and all achievements they have achieved. So no extra querying.

**Comment by nickserv** [comment]
I agree with your ideas on this. Besides, we can always have a cache in front of our entire application if we want to speed up profile loading.

Should we wait to close this issue until this is implemented, or did you intend on making this issue merely for planning purposes? If you did, please change the tag to "planning" and close this issue.
