### ISSUE TITLE
Real meetings...

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#31]
We should have real meetings...and define requirements...and something something be good software engineers.

**Comment by toroidal-code** [comment]
I definitely agree with this.

**Comment by nickserv** [comment]
:+1:

Should I make a Doodle?

**Comment by kristenmills** [comment]
yeah

**Comment by kristenmills** [comment]
I'm making a wiki called Requirements. Update it at will.

**Comment by nickserv** [comment]
I'll probably make a Doodle with Kate tonight.

**Comment by nickserv** [comment]
I sent out the Doodle poll. If you got it, please fill it out. If you didn't, please let me know and I'll make sure you get an invite.

**Comment by nickserv** [comment]
The Doodle poll is closed, and I emailed everyone about the decided time and place for our weekly meetings.

We can update and/or add to our requirements during our next meeting if need be.
