### ISSUE TITLE
Github Integration

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#34]
While talking about code storage, I was thinking about how it might be a good idea to have the ability to login with github using OAuth. What are people's thought's on that.

**Comment by nickserv** [comment]
I like this idea since it makes our lives a lot easier, though I'd personally prefer we only do this if we relied on GitHub services like Gists or normal repos.

**Comment by nickserv** [comment]
We have been talking about this, and it seems like the general consensus is that we shouldn't use GitHub for login, we should always use our own login system. We may let users optionally connect their Codeflash accounts to their GitHub accounts, though.

Please close this issue if the above sounds good to you.
