### ISSUE TITLE
How is scoring working for a solution?

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#35]
We've probably gone over this before but can we settle on something concrete for this so I can add the right columns to the right tables.

**Comment by nickserv** [comment]
I would say, for now, just do upvotes - downvotes, and then maybe multiply that by scales based on language family difficulty and problem difficulty.

**Comment by smy2748** [comment]
I agree with Nick

Insofar as columns added, upvotes and downvotes on a solution should be sufficient.  As to how we will actually calculate the score from there will probably be based on the related problem's score, but we can decide how exactly the scoring works later.

**Comment by nickserv** [comment]
:+1:

**Comment by nickserv** [comment]
I have a super simple algorithm on feature/ui that just does upvotes - downvotes. Is this done for now or do we still need to plan more?

We can always do fancier calculation later, but I feel like this works for now.

**Comment by kristenmills** [comment]
I'm closing this because this method is implemented. It's called votes though.
