### ISSUE TITLE
Set up documentation with YARD

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#40]
We should probably have a rake task for this.

**Comment by kristenmills** [comment]
this doesn't need to be a separate issue from #41. So i'm going to close it.

**Comment by nickserv** [comment]
I disagree. This issue involves setting up rake tasks for YARD and getting it to play nice with Rails, while the other one involves actually documenting code.

**Comment by nickserv** [comment]
I'm going to reopen this, since we need a reminder to set up YARD and I feel like that's separate from actually documenting code.
