### ISSUE TITLE
Update all wiki pages based on recent decisions

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#46]
Also, try to remove questions from the wiki, especially if we already have an agreed answer for them.

**Comment by smy2748** [comment]
What decisions are you talking about, exactly?

**Comment by nickserv** [comment]
Recent changes in our ideas for stuff like code storage, auth, etc. Problem is though, we're not done deciding many things. However, they are some things that should still be updated, like the mention of code families under "Requirements".

**Comment by nickserv** [comment]
I'm going to close this, since we've already done it to an extent, and it's something we will need to keep doing continuously.
