### ISSUE TITLE
Languages pages

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#53]
What should go on the languages pages? I was thinking links to solutions in that language, maybe users who have listed said language as favorite language. Any other thoughts?

**Comment by nickserv** [comment]
I like those ideas. I was mainly thinking about language pages listing their solutions, though we could also show cool stats like language rank (in terms of popularity), most frequent users of a language, etc.

**Comment by kristenmills** [comment]
closing this because we decided against it.
