### ISSUE TITLE
Get some nice performance tips from Chrome's audit tools

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#57]

**Comment by smy2748** [comment]
Could you please explain what you mean by this?

**Comment by nickserv** [comment]
![](http://i.imgur.com/jYLffrl.png)

**Comment by smy2748** [comment]
k bro.

**Comment by nickserv** [comment]
I have considered all of Chrome's speed suggestions at this point.

I'll call this done for now, but there are still other places we can improve speed (like putting a cache in front of Rails).
