### ISSUE TITLE
Icon not a gif

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#58]
We are going to be ridiculed if our icon is not an animated gif.
![](http://www.reactiongifs.com/wp-content/uploads/2013/01/RageConan.gif)

**Comment by toroidal-code** [comment]
![cm-39003-650c9185383947](https://f.cloud.github.com/assets/2250579/142375/18372a58-72e6-11e2-86ea-778ea95af937.gif)
what? no. lol

**Comment by nickserv** [comment]
Why does it need to be a gif? -_-

**Comment by smy2748** [comment]
Why are you asking after closing the issue?

**Comment by toroidal-code** [comment]
Lol, I closed it on nick's computer.
