### ISSUE TITLE
Keep track of user up and down votes to avoid multiple votes

### ISSUE THREAD

**Issue by StacyJCarlos** [toroidal-code/codeflash#62]
We need to keep track of user up and down votes to prevent spamming and to allow seniority voting.

**Comment by kristenmills** [comment]
join table between profile and solutions with an up vote or downvote column

**Comment by nickserv** [comment]
Let's not implement seniority voting until we're done deciding on whether or not we want it.

**Comment by smy2748** [comment]
Even if we do want it at some point, there probably won't be a need to implement it up front.  The creation of the join table, however, is necessary.

**Comment by nickserv** [comment]
Agreed.

**Comment by nickserv** [comment]
We need validation to ensure that users can only vote on posts once, along with additional view things so the user can actually vote.

**Comment by StacyJCarlos** [comment]
It shouldn't take that long to implement vote tracking, but we need to ensure the health of the votes. For this I recommend a voting supplement for every user.

**Comment by nickserv** [comment]
I do not feel that the term "supplements" is family-friendly, as small children may not understand what it means. As a result, I think we should implement Poffin support for votes.

**Comment by toroidal-code** [comment]
As this is now a circle. Closed.

**Comment by kristenmills** [comment]
We actually need this guys

**Comment by nickserv** [comment]
Agreed.

**Comment by smy2748** [comment]
:+1:

**Comment by toroidal-code** [comment]
Poffins? really guys?

**Comment by toroidal-code** [comment]
Has this been done or not?

**Comment by kristenmills** [comment]
not yet

**Comment by toroidal-code** [comment]
how do we want to implement this? profiles_voted column on the solution model, or a solutions_voted column on the profiles model?

**Comment by kristenmills** [comment]
Join table. Read above
