### ISSUE TITLE
Should we rename user to account and profile to user?

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#63]

**Comment by kristenmills** [comment]
Effort.....

**Comment by smy2748** [comment]
If it's not fixed, don't break it.  Or something...

**Comment by kristenmills** [comment]
We can change routing if we need too.

**Comment by nickserv** [comment]
I kind of want to, I think it would be a lot more intuitive that way.

**Comment by nickserv** [comment]
Well, looking at the system now and how users hold on to profiles that contain the user's work, I feel like it would be weird to do these renames. I'm thinking we should drop this idea and close this issue. Does anyone else agree?

**Comment by kristenmills** [comment]
I never actually thought it was necessary.

**Comment by nickserv** [comment]
Alright, it seems like people aren't crazy about this, so I'll close it.
