### ISSUE TITLE
america.html is not included

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#69]
Must be included.

**Comment by nickserv** [comment]
:+1:

**Comment by StacyJCarlos** [comment]
Normally I would agree, but I see only one thing that could be improved. Although we do expect the majority of the audience to be in the US, we may have people that access our site from various other countries. To solve this I propose we implement a dynamic flag that will correspond to the country the user is in. I think this would make the error page feel a little more personal.

**Comment by kristenmills** [comment]
**Also**: Lolol 69 hahah

**Comment by toroidal-code** [comment]
Circle is closed
