### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by smy2748** [toroidal-code/codeflash#7]
Insofar as dealing with authentication, the standard flow to follow is:
1. When a user registers, hash whatever password they give using a random salt and store the salt and hashed password in the db.
2. Whenever a user goes to log in, retrieve the hashed password and salt from the db, hash the password they provided with the salt, and then compared the hashed passwords.  

Really, we just need to find a hashing algorithm that's been implemented in Ruby and doesn't have the letters MD followed by a number.  Having something to generate a half-decent salt would be nice as well, but we can improvise if we can't find anything good.

**Comment by smy2748** [comment]
So there's this: http://www.ruby-doc.org/stdlib-1.9.3/libdoc/digest/rdoc/Digest/SHA2.html

I'm good with using SHA2 until SHA3 is implemented in Ruby.

**Comment by kristenmills** [comment]
I'm down with SHA2...at least for now.

**Comment by nickserv** [comment]
Should we look into using an auth/accounts gem that would do this for us, like [Clearance](http://github.com/thoughtbot/clearance)?

**Comment by smy2748** [comment]
We could, we'll have to look into how it works (both for practical and security-oriented purposes) and how it would interact with our User models.

**Comment by nickserv** [comment]
Alright. Do we want a separate issue for researching into Clearance and possibly other similar things?

**Comment by toroidal-code** [comment]
SHA-3 is implemented in the digest-sha3 gem.

**Comment by kristenmills** [comment]
So i'm looking into things like Devise and OmniAuth right now. I'm going to test a couple things out and see how they work. So i'm assigning this task to myself.

**Comment by nickserv** [comment]
We've already merged in Kristen's work on Devise integration (it's currently in dev and might end up in master soon). Kristen, feel free to close this issue now if you feel it's done.
