### ISSUE TITLE
User cannot log in with username on the /login page

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#71]
Steps:
1. Visit `/login` in a browser with HTML 5 form validation (Chrome and Firefox will work).
2. Type in your username. Note the red highlight on the text field (this should work on all browsers with JavaScript).
3. Type in your password and try to login. Depending on your browser, you may be stopped with the message "Please enter an email address.", preventing you from logging in.

Notes:
- This is not an issue on the home page (which has the compact version of the login form).
- This is a client side issue that only occurs on certain browsers. Most likely, we told Rails that the field should be an email field, so the browser assumes that the field must contain valid email addresses. As a result, most usernames will not work (unless they look like email addresses).

**Comment by kristenmills** [comment]
I might have forgot to change it to a non email field. I can change it. That's browser specific though i guess. I have no problems logging in on safari even though it highlights red.

**Comment by kristenmills** [comment]
yay hotfixes

**Comment by smy2748** [comment]
During your crypto meeting?  SHAME SHAME SHAME.

![BillOwlB](https://f.cloud.github.com/assets/1071849/143566/1490ac1c-73b3-11e2-80ad-c655a282182e.png)
