### ISSUE TITLE
Remove all GitHub support

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#78]
:(

**Comment by kristenmills** [comment]
?

**Comment by kristenmills** [comment]
I still think we should have linked github.

**Comment by toroidal-code** [comment]
I agree that we should have some sort of reference to github, but hooking into github's api seems a little much at this point.

**Comment by nickserv** [comment]
We can always let users have links to the GitHub profiles, instead of requiring that they give us access to their GitHub account via GitHub's API.

**Comment by kristenmills** [comment]
i still think logging with github is a good idea. But if you guys are against it, whatever.

**Comment by toroidal-code** [comment]
You mean logging in with github usernames? If we can get that to work, I'm not against it.

**Comment by kristenmills** [comment]
Devise has built in support for it.

**Comment by toroidal-code** [comment]
Hmm. okay. so I can bypass sign up  and just login with my github credentials?

**Comment by kristenmills** [comment]
Yeah. as soon as i enable it. I have us already registered on github for it.

**Comment by toroidal-code** [comment]
okay, then I would rather keep that feature.

**Comment by nickserv** [comment]
Alright, let's do that. So do we still need the OmniAuth gem?

**Comment by kristenmills** [comment]
yeah. We are still using OmniAuth but Devise has built in OmniAuth integration. I have it implemented.

**Comment by nickserv** [comment]
So, does anything need to be removed at this point, or is this issue done?
