### ISSUE TITLE
Code solution storage

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#8]
How are we going to handle this?

I was originally thinking using a GitHub repo or Gists along with GitHub's API, but that would start getting messy in terms of user permissions on the GitHub end of things. However, I'm still liking the idea of using git for easier offline work, versioning, and easy cloning/pushing. We could look into wrapping around Git with the sort of gems that GitHub and GitLab would use.

Ideas:
- GitHub repo for the organization
- GitHub repos for each user
- Gists for each user
- Plain text files stored on the server, with normal download/upload stuff
- Git repos on the server, similar to GitHub/GitLab

Please let me know if you have any other ideas, or comments on my existing ones.

**Comment by kristenmills** [comment]
So what if we embed the ace editor and then using github's API, create anonymous gists. 
And we can even just use something like [octokit](https://github.com/pengwynn/octokit) which is a really simple wrapper around the Github API. 
We should also probably support file uploads but we can deal with that later.

**Comment by nickserv** [comment]
One of my first ideas was to use Gists. I think they would be great for storing quick files like these over time (and we wouldn't have to worry about storing code ourselves and related security concerns).

However, there are a some issues that make me feel less comfortable about wanting to use Gists:
1) Should the Gists be anonymous? It would be nice if a user could claim their own work on the Gist site. However, that would require GitHub logins.
2) Will we be able to make enough Gists via the API at the frequency we will require?
3) Would be be reinventing the wheel too much if we use Gists for storage but add our own editor, comment system, etc. to our site (when Gist already has these features)?
4) What if a Gist is changed via the Gist site? How will our solution pages handle that? This may not be an issue if we use anonymous issues, though (since I don't think they can be updated).

**Edit**:
Also, Ace and Octokit seem pretty awesome. I'd agree with using those if we decided to implement that sort of functionality ourselves.

**Comment by kristenmills** [comment]
1) We can use OAuth if we want to. 
2) We get sixty an hour if we use no OAuth but if we use OAuth we get 5000. Neither should cause us that much grief for now.  We should still have anonymous available if we do Oauth.
3) Well I mean it's mostly for display and storage. So idk.
4) We would be embedding the gist not storing the data so it would update accordingly.

**Comment by nickserv** [comment]
1) True, I was thinking about that earlier. That would mean we wouldn't have to implement our own auth/login system, right?
2) Sounds good. Are there higher paying tiers available?
3) I was thinking though, will we want comments on every solution? If so, they may get unwanted overlap with Gist comments.
4) I meant in terms of scoring and updating the view. The view would probably be updated just fine as you're saying, but what if a user makes significant improvements to their solution and other users don't notice it? What if someone tries to do malicious stuff, like copying someone else's code, waiting until they get a lot of votes, and then changing it?

**Comment by kristenmills** [comment]
1) Well i was thinking giving the user the option. So we'd still have to in my opinion.
2) Not that i'm aware of.
3) I honestly don't think that is of concern because it's not like we are going to be sending our users to github to look at the code. We are expecting them to comment on our site. 
4) This part does concern me. Maybe gists aren't the right solution because of this. But they are also versioned so maybe we can only have the first version up? Is that a thing we can do?

**Comment by nickserv** [comment]
1) Ah, alright. That could get tricky though.
2) Hopefully we can stick under the limits then.
3) Yeah, that's a good point.
4) Well, because of the versioning support, I guess we could just make sure that we display a specific version of the Gist at all times (assuming that's possible via their API). We could also optionally let users update their Gists, but then we'd have to worry about rules and scoring tweaks to go along with that.

**Comment by kristenmills** [comment]
1) I'm thinking for now we just do it based on whether the user is logged in through github or not. But then we can give logged in users an option later. 
2) I don't think it will be a big deal. Are we really going to have 5000 github users and 60 anonymous users creating code every hour? 
4) When you create a gist, you get the raw url back as a response which contains version number. So if we store the raw url in the database, we will always have first version. So that actually shouldn't be an issue.

**Comment by nickserv** [comment]
I'm liking the Gist idea, let's stick with that. The only issue though, is what happens if a user deletes a Gist that's used by a Codeflash solution? We'd either be losing data in our app or we'd have to cache **all** our code to prevent  it from going away.

**Comment by smy2748** [comment]
Storing files IN THE CLOUD (Amazon s3 or something) could work.  We'd just have to cap the size of the files that are allowed to be uploaded.

**Comment by toroidal-code** [comment]
I like the idea of using S3 or other cloud system. It would allow us to manage all creation and deletion and permissions of submissions.

**Comment by kristenmills** [comment]
s3 is a good idea

**Comment by nickserv** [comment]
:+1:

**Comment by smy2748** [comment]
:+1:

**Comment by kristenmills** [comment]
can we close this issue? I think everyone agrees on this.

**Comment by nickserv** [comment]
So, we would be using S3 for file storage and completely ditching anything GitHub, correct?

**Comment by toroidal-code** [comment]
Yes.

**Comment by nickserv** [comment]
I'll close this, let me know if anyone opposes.
