### ISSUE TITLE
Should we have multiple views for both sign up and login?

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#85]
Currently, we have new.html.erb and _compact. html.erb views for both Sessions and Registrations. The compact partials are used on the home page, while the normal forms are used on the dedicated login and sign up pages.

We have duplicated code now, but maybe we can just make responsive versions of the new views instead.

**Comment by StacyJCarlos** [comment]
I agree with Nick. The home page sign up is pretty obvious, but I think another exclusive registration page would be nice considering most all good websites have that nowadays.

**Comment by nickserv** [comment]
Actually, that's not what I meant by multiple views. I agree that we should have two pages each for login and registration, but I was asking if we should have two separate views for login/registration or if we should have one that's loaded as a partial into both pages. So it's a matter of duplicate code in the backend. Sorry for the confusion.

**Comment by StacyJCarlos** [comment]
Oh, I don't think we need multiple views for the back end. That seems like that would just be a matter of choosing the one we like most.

**Comment by nickserv** [comment]
However, the views would be for two very different displays of the form (size-wise). Though we could probably just be super hip and do it responsively.

**Comment by StacyJCarlos** [comment]
That does sound hip and current, and we might need them later on. As far as right not so  much, but we should definitely keep this in the back our minds.

**Comment by nickserv** [comment]
I think I should just stick with my idea of having one responsive partial for each of the login and signup pages.
