### ISSUE TITLE
How should we be handling filtering on the problems page?

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#86]
Kate and I were discussing how we want to do the filtering of the problems on the problem pages. We really have two major options: Update the problems controller and create pages for them or have javascript filter the divs on the index page. 

I think personally that we should do it with the controller. It will be cleaner probably.  What do other think?

**Comment by StacyJCarlos** [comment]
I'm not sure how to do it in rails, but I know doing it in javascript may be a little bit of an annoyance. So far keeping the majority of things like this on rails seems like it would make the overall project easier rather than having to switch between javascript and rails.

**Comment by nickserv** [comment]
Client-side (AJAX) advantages:
- users don't need to receive full HTTP requests just to view similar versinos of the page, so loading different filter settings should be a bit faster
- easier to make pretty animations in the UI

Server-side (Rails controller) advantages:
- client-side requires JavaScript to be enabled, so server-side is safer
- because of the previous point, this should probably be used as a fallback from AJAX anyway
- AJAX seems kind of annoying to implement, and if we just do server-side filtering, we won't have to worry about AJAX

**Comment by nickserv** [comment]
@StacyJCarlos Yes, doing it in JavaScript will be more annoying, but there are huge advantages to using AJAX. Also, we shouldn't have to worry about avoiding writing JavaScript. It's good practice to add code to the front end when it's decided that it would work nicer on the front end, even if that means having to implement it in JavaScript. Besides, jQuery has awesome tools for working with AJAX.

**Comment by StacyJCarlos** [comment]
@thenickperson Agreed

**Comment by nickserv** [comment]
I think we should do this client-side with AJAX, with a **complete** server-side fallback if the user doesn't have JavaScript. It's a lot more work, but it's the best of both worlds. Agreed?

**Comment by smy2748** [comment]
So if we are going to have all the problems load onto one page without any sort of pagination occurring, then the javascript idea seems the best.  If we plan on paginating the problems, then we really don't want to be doing this in javascript and a new search page would probably be best.

**Comment by nickserv** [comment]
I think we should do pagination, since infinite scrolling wouldn't work well with the footer.

**Comment by nickserv** [comment]
@kristenmills Did you decide on this yet?

**Comment by kristenmills** [comment]
yeah. We are doing ajax with server side fallback.

**Comment by nickserv** [comment]
Nice. Since this is a planning issue, want to close it?

**Comment by kristenmills** [comment]
yeah
