### ISSUE TITLE
Categories and short names for problems

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#87]
- [x] create the category model
- [x] add the has_and_belongs_to_many relationship with categories and problems
- [x] create the join table
- [x] add the short name column to problems
- [x] change the routing so that a problem can be accessed by both short name and id

**Comment by nickserv** [comment]
Have we reached final decisions on what kinds of categories we're going to have? Will it be by difficulty, paradigm used to solve, field of problem, etc.?

**Comment by kristenmills** [comment]
That should be a separate issue since that's irrelevant to the creation process.

**Comment by nickserv** [comment]
Alright, I'll make one.
