### ISSUE TITLE
Get rid of language views and controllers?

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#88]
Do we need them? I think we just need the model at this point.

**Comment by nickserv** [comment]
I would otherwise be in favor of this, but how could developers get our most recent language list via our API without the JSON views for languages?

**Comment by kristenmills** [comment]
valid.

**Comment by nickserv** [comment]
On the other hand, wouldn't it be nice if we could have a list of languages for the user (HTML) somewhere? It would be more of a simple list than a fancy UI, but it would still be cool to see all languages in one place, unless the Problems/Solutions UI is enough.

**Comment by kristenmills** [comment]
i thought kate didn't want that.

**Comment by kristenmills** [comment]
i'm closing this.
