### ISSUE TITLE
Profile scaffold

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#9]
Should we make a profile scaffold and have the profile be more of the public facing stuff of a user?  Just to split it up and all.

**Comment by nickserv** [comment]
See http://stackoverflow.com/questions/3947384/rails-users-has-one-profile-vs-show-page

**Comment by kristenmills** [comment]
Solution We are doing profile.

**Comment by kristenmills** [comment]
Lies.  no profile.  Putting it in user
