### ISSUE TITLE
User cannot submit solutions to problems

### ISSUE THREAD

**Issue by StacyJCarlos** [toroidal-code/codeflash#92]

**Comment by nickserv** [comment]
To be more specific, when you type code into the Ace editor and try to submit it, Rails thinks you didn't submit any code. Therefore, the validations fail and you can't create your solution.

This is probably a client-side JavaScript issue.

**Comment by kristenmills** [comment]
wait what?

**Comment by toroidal-code** [comment]
Fixed.
