### ISSUE TITLE
Should we start assigning issues to sprints?

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#97]
I was thinking it might be nice to start making milestones due every 1/2 weeks, and then we could assign issues between sprints. However, we're getting tons of work done without strict due times, so we might not need this.

**Comment by smy2748** [comment]
Meh.  SCRUM tends to fall apart anyways, so just let it be for the moment.

**Comment by toroidal-code** [comment]
Agreed

**Comment by nickserv** [comment]
Alright, I was thinking it might be overkill anyway.

Let's not do sprints for now. However, if progress starts getting inconsistent in the future, we can always consider setting up sprints to remind us to keep up the pace. I just don't think we need it right now.
