### ISSUE TITLE
Repair tests for solution controller

### ISSUE THREAD

**Issue by toroidal-code** [toroidal-code/codeflash#99]
Due to switching the solution model from  `belongs_to :user` to `belongs_to :profile`, the following tests have broken in solutions_controller_test.rb:
- [x] should create solution
- [x] should get index
- [x] should get new
- [x] should show solution

**Comment by toroidal-code** [comment]
I think my comment explains everything.

**Comment by kristenmills** [comment]
sorry i read that wrong

**Comment by toroidal-code** [comment]
LOL okay.

**Comment by kristenmills** [comment]
did you change the tests...and the database...and everything.

**Comment by toroidal-code** [comment]
the database actually doesn't need to get changed. The tests do. I do not know how to test.

**Comment by kristenmills** [comment]
There is a lot wrong with this commit 55b593c19eb1452e81ed4675e74b8043d33e9418 That's what's really broken.

**Comment by toroidal-code** [comment]
could you do line comments and tell me?

**Comment by toroidal-code** [comment]
If you can fix all the problems in that commit, I don't have any problems with that.Please create a new branch though.

**Comment by kristenmills** [comment]
Okay.

**Comment by toroidal-code** [comment]
You have won a cookie. I will owe you.

**Comment by kristenmills** [comment]
:+1:
